---

apiVersion: v1
kind: Service
metadata:
  name: swiggy-food-service
  namespace: srinu
  labels:
    app: swiggy-food
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: swiggy-food
